const recipes = [
  ["air ", "water ", " rain"],
  ["water", "water", "sea"],
  ["water", "sea", "ocean"],
  ["water", "fire", "steam"],
  ["water", "earth", "mud"],
  ["water", "air", "rain"],
  ["fire", "earth", "lava"],
  ["fire", "air", "energy"],
  ["fire", "mud", "brick"],
  ["earth", "earth", "pressure"],
  ["earth", "air", "dust"],
  ["earth", "steam", "geyser"],
  ["earth", "rain", "plant"],
  ["earth", "plant", "grass"],
  ["earth", "lava", "volcano"],
  ["earth", "energy", "earthquake"],
  ["earth", "earthquake", "mountain"],
  ["fire", "dust", "gunpowder"],
  ["fire", "plant", "tobacco"],
  ["fire", "gunpowder", "explosion"],
  ["air", "air", "pressure"],
  ["air", "steam", "cloud"],
  ["air", "lava", "stone"],
  ["plant", "plant", "garden"],
  ["sea", "sea", "ocean"],
];
export default recipes;
